config/routes.rb
Rails.application.routes.draw do

  get 'doses/new'

  get 'doses/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :cocktails do
      resources :doses, only: [ :new, :create ]
  end



  root to: "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  # Relations
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  # Validations
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  # Relations
  belongs_to :cocktail
  belongs_to :ingredient
  # Validations
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  # Filters
  before_destroy :check_child
  # Relations
  has_many :doses , dependent: :destroy
  has_many :cocktails, through: :doses

  # Validations
  validates :name, presence: true
  validates :name, uniqueness: true

  private
  def check_child
    raise ActiveRecord::InvalidForeignKey unless  self.doses.count == 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def update
    @cocktail.update(cocktails_params)
    redirect_to cocktails_path
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  def edit
  end

  def create
    @cocktail = Cocktail.new(cocktails_params)
     if @cocktail.save
      redirect_to cocktail_path(@cocktail)
     else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktails_params
    params.require(:cocktail).permit(:name, :doses, :ingredients)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(doses_params)
    @cocktail  = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
     if @dose.save
      redirect_to cocktail_path(@cocktail)
     else
      render :new
    end
  end

  # def destroy
  #   @dose = Dose.find(params[:id])
  #   @dose.destroy
  #   redirect_to cocktail_path
  # end

  private

  def set_dose
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def doses_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<!-- Form using simple form -->
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name, placeholder: "Mojito"%>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

app/views/cocktails/index.html.erb
<h1 class= "text-center">Cocktails</h1>
<div class= "text-center">
  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <h2><%= cocktail.name %></h2>

        <%= link_to "Check it out!", cocktail_path(cocktail), class: "btn-xs btn-primary" %>
        <%= link_to "Edit it!", edit_cocktail_path(cocktail), class: "btn-xs btn-primary"%>
        <%= link_to "Eliminate it!", cocktail_path(cocktail), method: :delete, class: "btn-xs btn-primary"%>
        </div>

        <% end %>

    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1 class= "text-center">Create a cocktail</h1>
<%= render "form" %>

app/views/cocktails/show.html.erb
<!-- Show Form -->
  <h1 class="text-center"><%= @cocktail.name %></h1>
  <div class="text-center">

    <%= link_to "Go back!", cocktails_path%>
  </div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>